# Conda environment for Nail Salon AI Backend
name: nail-salon-ai
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  
  # Web Framework
  - fastapi=0.104
  - uvicorn=0.24
  
  # Database
  - sqlalchemy=2.0
  - asyncpg=0.29
  - psycopg2=2.9
  - alembic=1.12
  
  # Data Science & ML (conda has pre-compiled binaries!)
  - scikit-learn=1.3
  - pandas=2.1
  - numpy=1.26
  
  # Security
  - cryptography
  
  # Redis
  - redis-py=5.0
  
  # Utilities
  - pydantic=2.5
  - httpx=0.25
  - python-dateutil
  
  # Pip-only packages
  - pip
  - pip:
    - python-multipart==0.0.6
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - python-dotenv==1.0.0
    - pydantic-settings==2.1.0
    - email-validator
    - aiomysql==0.2.0
    - pymssql==2.2.11
    - celery==5.3.4
    - flower==2.0.1
    - vanna==0.3.4
    - ollama==0.1.6
    - chromadb==0.4.18
    - prophet==1.1.5
    - prometheus-client==0.19.0
    - sentry-sdk==1.38.0
    - chardet==5.2.0
    - aiofiles==23.2.1
    - hiredis==2.2.3

